:!last-update-label:
:icons: font

== Installation and setup instructions

. Create a Python virtual environment.
. Install the app by running `pip install .`.
+
TIP: Use the `-e` option to install in editable mode in development, like so: `pip install -e .`.
. Install environment-specific dependencies by running `pip install --group <environment>`, where `<environment>` could be any of `dev`, `test` or `prod` for development, testing and production, respectively. Additionally, the `test_dev` group can be installed to ease development of tests.
. Set the `PROFILE` environment variable to either `development` or `production` to configure the app according to the deploy. This setting is not required for a testing deploy.
. In the `production` profile, set the secret key used for securely signing cookies by setting the `QUART_SECRET_KEY` environment variable to the key value. To generate a secret key, run the following code:
+
[source, python]
----
import secrets
print(secrets.token_urlsafe(16))
----
+
NOTE: In the `development` profile, the secret key is hard-coded to 'dev' as there is no security threat.
. In the `production` profile, configure the work factor of the bcrypt password hashing algorithm by setting the number of rounds as the `BCRYPT_LOG_ROUNDS` environment variable. The larger the number of rounds, the more work will have to be done (exponentially) to hash the passwords. It should be tuned such that it takes about 1 second to verify a password on the system.
+
[IMPORTANT]
--
This time-consuming behaviour is intentional, to make it difficult for attackers to crack the password using brute-force methods, but not so costly that it puts excessive burden on the system or irritates users.

The work factor should be tuned for the deploy system since the performance varies drastically from system to system.

Refer to https://docs.spring.io/spring-security/reference/features/authentication/password-storage.html#authentication-password-storage-history[this explanation] for more on password storage security.
--
+
NOTE: In the `development` profile, the work factor is set to the minimum value of 4 to reduce the time for password verification as there is no security threat.
. Set the following environment variables used by the application to connect to the PostgreSQL database server:
+
[%autowidth.stretch]
|===
|Variable name |Description

|`DB_USERNAME`
|The name of the database user account for this application.

|`DB_PASSWORD`
|The password of the database user account.

|`DB_HOST`
|The hostname or IP address of the database server.

|`DB_PORT`
|The port number of the database server.

|`DB_NAME`
|The name of the database for this application.
|===
+
The database user is required to have the following privileges:
+
** `CONNECT` privilege on the database.
** `USAGE` privilege on the schema.
** `SELECT`, `INSERT`, `UPDATE` and `DELETE` default privileges on the schema tables.
** `USAGE` default privilege on the schema sequences.
. In `development` and `production` deploys, create the database schema objects by running the `quart create_db_schema_objects` command, if not done already. Running this command requires the database user to be the owner of the schema.

== Testing

The database user in a testing deploy is required to be the owner of the database schema. The schema will be recreated before each test to ensure test isolation.

Run the `pytest` command to run the unit tests.

== Data model

Refer to xref:docs/data_model.adoc[this document].