:!last-update-label:
:icons: font

== Installation and setup instructions:

. Create a Python virtual environment.
. Install the app by running `pip install .`.
. Set the `PROFILE` environment variable to either `development` or `production` to configure the app according to the deploy. This setting is not required for a testing deploy. Also install environment-specific dependencies by running `pip install --group <environment>`, where `<environment>` could be any of `dev`, `test` or `prod` for development, testing and production, respectively.
. In the `production` profile, set the secret key used for securely signing cookies by setting the `QUART_SECRET_KEY` environment variable to the key value. To generate a secret key, run the following code:
+
[source, python]
----
import secrets
print(secrets.token_urlsafe(16))
----
+
NOTE: In the `development` profile, the secret key is hard-coded to 'dev' as there is no security threat.
. In the `production` profile, configure the work factor of the bcrypt password hashing algorithm by setting the number of rounds as the `BCRYPT_LOG_ROUNDS` environment variable. The larger the number of rounds, the more work will have to be done (exponentially) to hash the passwords. It should be tuned such that it takes about 1 second to verify a password on the system.
+
[IMPORTANT]
--
This time-consuming behaviour is intentional, to make it difficult for attackers to crack the password using brute-force methods, but not so costly that it puts excessive burden on the system or irritates users.

The work factor should be tuned for the deploy system since the performance varies drastically from system to system.
--
+
NOTE: In the `development` profile, the work factor is set to the minimum value of 4 to reduce the time for password verification as there is no security threat.
. In the `development` profile, the default database used is a deployment-specific SQLite file database. This requires the app instance folder to be created first, which is where the SQLite database file will reside. Run the `quart create_instance_folder` command to create the app instance folder. Alternatively, set the `DB_SYSTEM` environment variable to `postgresql` to configure the app to connect to a PostgreSQL database server. Also install the driver of the database used by running `pip install --group <db_system>`, where `<db_system>` could be `sqlite` or `postgresql`.
. When using a PostgreSQL database, set the following environment variables used by the application to connect to the database server:
+
[%autowidth.stretch]
|===
|Variable name |Description

|`DB_USERNAME`
|The name of the database user account for this application.

|`DB_PASSWORD`
|The password of the database user account.

|`DB_HOST`
|The hostname or IP address of the database server.

|`DB_PORT`
|The port number of the database server.

|`DB_NAME`
|The name of the database for this application.
|===
. Create the database schema objects by running the `quart create_db_schema_objects` command, if not done already.

== Testing
Run the `pytest` command to run the unit tests.

== Data model
Refer to xref:docs/data_model.adoc[this document].